tennisclub/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name="index"),
    path('logout', views.logout_view, name='logout'),
    path('kontakt/', views.kontakt_view, name="kontakt"),
    path('verein/', views.verein_view, name="verein"),
    path('verein/beitrag', views.beitrag_view, name="beitrag"),
    path('verein/team', views.team_view, name="team"),
    path('verein/rückblick', views.rückblick_view, name="rückblick"),


    path('verein/termine', views.termine_view, name="termine"),
    path('verein/anfahrt/', views.anfahrt_view, name="anfahrt"),
    path('createtermin', views.createtermin_view, name='createtermin'),
    path('<str:uuid>/terminbearbeiten', views.terminedit_view, name='terminedit'),
    path('<str:uuid>/termindelete', views.termindelete_view, name='termindelete'),


    path('blog/', views.blog_view, name='blog'),
    path('createblogPost', views.createblogPost_view, name='createblogPost'),
    path('<str:uuid>/blogPostbearbeiten', views.blogPostedit_view, name='blogPostedit'),
    path('<str:uuid>/blogPostdelete', views.blogPostdelete_view, name='blogPostdelete'),
    path('blog/<str:uuid>', views.blogPostDetail_view, name='detail'),


    path('tennis/schule', views.schule_view, name="schule"),
    path('tennis/courts', views.courts_view, name="courts"),
    path('tennis/regeln', views.regeln_view, name="regeln"),
    path('sitemap',views.sitemap_view, name='sitemap'),
    path('impressum',views.impressum_view, name='impressum'),
    path('login/', views.login_view, name="login"),
    
    path('tennis/courts/teppichboden_preise', views.courts_teppichboden_preise_view, name="teppichboden_preise"),
    path('tennis/courts/Traglufthalle_preise', views.courts_Traglufthalle_preise_preise_view, name="Traglufthalle_preise"),
    
    path('tennis/courts/teppichbodenhalle', views.courts_teppichbodenhalle, name="courts_teppichbodenhalle"),
    path('tennis/courts/traglufthalle', views.courts_traglufthalle, name="courts_traglufthalle"),
    

    path('galerie/', views.galerie_view, name="galerie"),
    path('addgaleriebild', views.addgaleriebild_view, name='addgaleriebild'),
    path('<str:uuid>/galeriebildbearbeiten', views.galeriebildbearbeiten_view, name='galeriebildbearbeiten'),
    path('<str:uuid>/galeriebilddelete', views.galeriebilddelete_view, name='galeriebilddelete'),

    path('blog/<str:uuid>/kommentarErstellen', views.kommentar_erstellen_view, name="kommentarerstellen"),
    path('blog/<str:uuid>/kommentarDelete', views.kommentar_delete_view),
    path('stoperror', views.stoperror_view),
]

tennisclub/models.py
from datetime import date
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
import uuid

class Termine(models.Model):
    bezeichnung = models.CharField(max_length=100, verbose_name='Bezeichnung *')
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(verbose_name='Datum *')
    time = models.TimeField(verbose_name='Uhrzeit', blank=True, null=True)
    location = models.CharField(max_length=100, verbose_name='Standort', blank=True, null=True)

    def __str__(self):
        return self.bezeichnung[:30] + '...'

class BlogPost(models.Model):
    titel = models.CharField(max_length=100, verbose_name='Titel *')
    creation = models.DateTimeField(auto_now_add=True, blank=True, editable=False)
    inhalt = models.CharField(max_length=2000, verbose_name='Inhalt *')
    bild = models.ImageField(blank=True, default="tennisball.png")
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date= models.DateField(verbose_name='Datum *')
    standort = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.titel[:30] + '...'

    def snippet(self):
        return self.inhalt[:75] + '...'

class Galerie(models.Model):
    bild = models.ImageField(verbose_name='Bild *')
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    beschreibung = models.CharField(blank=True, max_length=100, verbose_name='Beschreibung', null=True)
    creation = models.DateTimeField(auto_now_add=True, blank=True, editable=False)
    date= models.DateField(verbose_name='Datum', blank=True, null=True)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    standort = models.CharField(blank=True, max_length=100, verbose_name='Standort', null=True)

class Kommentar(models.Model):
    autor = models.CharField(max_length=100, verbose_name='Anzeigename *')
    inhalt = models.CharField(max_length=200, verbose_name='Inhalt *')
    date = models.DateField(auto_now_add=True)
    blogPost_reffering = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    email = models.EmailField(verbose_name='Email *', default='')

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    

tennisclub/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class TermineForm(forms.ModelForm):
    class Meta:
        model = models.Termine
        fields = ('bezeichnung', 'date', 'time', 'location',)
        widgets = {
            'date': DateInput(attrs={
                'class': "form-control",
                'placeholder': 'Tag Monat Jahr',
                }),
            'time': TimeInput(attrs={
                'class': "form-control",
               
                }),
            'bezeichnung': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Bezeichnung'
                }),
            'location': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Standort'
                }),

        }

class BlogForm(forms.ModelForm):
    class Meta:
        model = models.BlogPost
        fields = ('titel', 'inhalt', 'date', 'bild', 'standort',)
        widgets = {
            'date': DateInput(attrs={
                'class': "form-control",
                'placeholder': 'Tag Monat Jahr',
                }),
            'bild': forms.FileInput(attrs={
                    'class': "form-control",
                }),
            'standort': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Standort'
                }),
            'inhalt': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Inhalt'
                }),
            'titel': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Titel'
                }),
            
            
        }

class GalerieForm(forms.ModelForm):
    class Meta:
        model = models.Galerie
        fields = ('bild', 'date', 'beschreibung', 'standort')
        widgets = {
            'date': DateInput(attrs={
                'class': "form-control",
                'placeholder': 'Tag Monat Jahr',
                }),
            'beschreibung': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Beschreibung'
                }),
                'standort': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Standort'
                }),
                'bild': forms.FileInput(attrs={
                    'class': "form-control",
                })
        }

class KommentarForm(forms.ModelForm):
    class Meta:
        model = models.Kommentar
        fields = ('autor', 'inhalt', 'email',)
        widgets = {
            
            'autor': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Anzeigename'
                }),
                'inhalt': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Inhalt'
                }),
                'email': forms.EmailInput(attrs={
                'class': "form-control",
                'placeholder': 'Email'
                })
        }

tennisclub/views.py
import uu
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from datetime import date, timedelta
from django.contrib.auth import login, logout
from .models import *
from .forms import *
from .filters import *

def index_view(request):
    startdate = date.today()
    enddate = startdate - timedelta(days=14)
    blogPosts = BlogPost.objects.all().filter(date__range=[enddate, startdate]).order_by('-date')[:3]
    termineenddate = startdate + timedelta(days=14)
    nextTermin = Termine.objects.all().filter(date__range=[startdate, termineenddate]).order_by('date')[:1].first()
    print(termineenddate)
    print(nextTermin)
    return render(request, 'index.html', {'blogPosts': blogPosts, 'termin': nextTermin})

def kontakt_view(request):
    return render(request, 'kontakt.html')

def beitrag_view(request):
    return render(request, 'beitrag.html')

def team_view(request):
    return render(request, 'team.html')
def rückblick_view(request):
    return render(request, 'heim.html')

def termine_view(request):
    
    termine = Termine.objects.all().order_by('date')
    myFilter = TerminFilter(request.GET, queryset=termine) 
    termine = myFilter.qs

    termineForm = TermineForm()

    return render(request, 'termine.html', {'termine':termine, 'termineForm': termineForm, 'myFilter': myFilter})


def createtermin_view(request):

    termineForm = TermineForm(data=request.POST)
    if termineForm.is_valid() and request.user.is_superuser:
        instance = termineForm.save(commit=False)
        instance.autor = request.user
        instance.save()
    return redirect('termine')

def terminedit_view(request, uuid):
    termin = Termine.objects.get(uuid=uuid)
    if request.method=='POST' and request.user.is_superuser:
        termin.bezeichnung = request.POST.get('editbezeichnung')
        if request.POST.get('editdate') != "":
            termin.date = request.POST.get('editdate')
        if request.POST.get('edittime') != "":
            termin.time = request.POST.get('edittime')
        termin.location = request.POST.get('editlocation')
        termin.save()
        
    return redirect('termine')

def termindelete_view(request, uuid ):
    termin = Termine.objects.get(uuid=uuid)
    
    if request.method=='POST' and request.user.is_superuser:
        termin.delete()
    return redirect('termine')

def schule_view(request):
    return render(request, 'schule.html')
def anfahrt_view(request):
    return render(request, 'anfahrt.html')
def courts_view(request):
    return render(request, 'courts.html')
def courts_teppichboden_preise_view(request):
    return render(request, 'courts_teppichboden_preise_view.html')
def courts_Traglufthalle_preise_preise_view(request):
    return render(request, 'courts_Traglufthalle_preise_preise_view.html')
def courts_teppichbodenhalle(request):
    return render(request, 'teppichbodenhalle.html')
def courts_traglufthalle(request):
    return render(request, 'traglufthalle.html')



def regeln_view(request):
    return render(request, 'regeln.html')

def sitemap_view(request):
    return render(request, 'sitemap.html')
def impressum_view(request):
    return render(request, 'impressum.html')
def verein_view(request):
    return render(request, 'verein.html')


def login_view(request):
    
    if request.method == 'POST':
        loginform = AuthenticationForm(data=request.POST)
        if loginform.is_valid():
            
            user = loginform.get_user()
            
            login(request, user)
                       
            return redirect('/')
            
    else:
        loginform = AuthenticationForm()
    return render(request, 'login.html', {'loginform':loginform})


def blog_view(request):

    blogForm = BlogForm()
    blogPosts = BlogPost.objects.all().order_by('-date')
    myFilter = BlogFilter(request.GET, queryset=blogPosts) 
    blogPosts = myFilter.qs

    return render(request, 'blog.html', {'blogForm': blogForm, 'blogPosts': blogPosts, 'myFilter': myFilter, })


def createblogPost_view(request):

    blogForm = BlogForm(request.POST, request.FILES)
    print(blogForm)
    if blogForm.is_valid() and request.user.is_superuser:
        print('hello?')
        instance = blogForm.save(commit=False)
        instance.autor = request.user
        instance.save()
    return redirect('blog')

def blogPostedit_view(request, uuid):
    blogPost = BlogPost.objects.get(uuid=uuid)
    if request.method=='POST' and request.user.is_superuser:
        blogPost.titel = request.POST.get('edittitel')
        blogPost.inhalt = request.POST.get('editinhalt')
 
        if request.POST.get('editdate') != "":
            blogPost.date = request.POST.get('editdate')
        print(request.FILES.get('editbild'))
        if request.FILES.get('editbild') != None:
            print(request.FILES.get('editbild'))
            blogPost.bild = request.FILES.get('editbild')
        print('Wenn du das hier alleine siehst hast du einen Fehler!')
        blogPost.standort = request.POST.get('editstandort')
        blogPost.save()
        
    return redirect('blog')

def blogPostdelete_view(request, uuid ):
    blogPost = BlogPost.objects.get(uuid=uuid)
    
    if request.method=='POST' and request.user.is_superuser and blogPost.autor == request.user:
        blogPost.delete()
    return redirect('blog')

def blogPostDetail_view(request, uuid):
    blogPost = BlogPost.objects.get(uuid=uuid)
    kommentare = Kommentar.objects.filter(blogPost_reffering__uuid = uuid)
    kommentarForm = KommentarForm
    
    return render(request, 'blogPostDetail.html', {'blogPost': blogPost, 'kommentarForm': kommentarForm, 'kommentare': kommentare})

def galerie_view(request):
    galerie = Galerie.objects.all()
    galerieForm = GalerieForm
    return render(request, 'galerie.html', {'galerie': galerie, 'galerieForm': galerieForm})

def addgaleriebild_view(request):
    if request.method == 'POST':
        galerieForm = GalerieForm(request.POST, request.FILES)
        if galerieForm.is_valid() and request.user.is_superuser:
            instance = galerieForm.save(commit=False)
            
            instance.autor = request.user
            instance.save()
    return redirect('galerie')

def galeriebildbearbeiten_view(request, uuid):
    bild = Galerie.objects.get(uuid=uuid)
    if request.method=='POST' and request.user.is_superuser:
        bild.beschreibung = request.POST.get('editbeschreibung')
 
        if request.POST.get('editdate') != "":
            bild.date = request.POST.get('editdate')
        if request.FILES.get('editbild') != None:
            bild.bild = request.FILES.get('editbild')
        bild.standort = request.POST.get('editstandort')
        bild.save()
        
    return redirect('galerie')

def galeriebilddelete_view(request, uuid ):
    bild = Galerie.objects.get(uuid=uuid)
    
    if request.method=='POST' and request.user.is_superuser:
        bild.delete()
    return redirect('galerie')


def logout_view(request):


    logout(request)
    return redirect('index')

def kommentar_erstellen_view(request, uuid):
    if request.method == 'POST':
        kommentarForm = KommentarForm(request.POST)
        print(kommentarForm)
        if kommentarForm.is_valid():
            instance = kommentarForm.save(commit=False)
            instance.blogPost_reffering = BlogPost.objects.get(uuid=uuid)
            print(instance.blogPost_reffering)
            instance.save()
            if 'error_message' in request.session:
                del request.session['error_message']
        else:
            request.session['error_message'] = 'Bitte trage eine valide Email ein'
            return redirect('/blog/' + uuid)
    return redirect('/blog/'+ uuid)

def kommentar_delete_view(request, uuid):
    if request.method == 'POST' and request.user.is_superuser:
        kommentar = Kommentar.objects.get(uuid=uuid)

        url = kommentar.blogPost_reffering.uuid
       
        kommentar.delete()
    return redirect('/blog/'+ str(url))

def stoperror_view(request):
    if 'error_message' in request.session:
                del request.session['error_message']

    url = request.META.get('HTTP_REFERER')
    return redirect(url)

    

tennisclub/templates/blog.html
{% extends 'base.html' %} {% block content %} {% load static %}

<h1>Blog</h1>
<hr />
<div class="filter">
  <div id="filter">
    <i id="filtericon" class="fas fa-filter"></i>
            <a id="filterreset" href="/blog">Filter zurücksetzen</a>
        {{blogPosts.count}} Artikel
  </div>

  <div class="blog_filter">
    <form method="get">
      {{myFilter.form}}
      <button
        class="btn btn-primary"
        style="text-align: center"
        type="submit"
        name="submit"
        value="Search"
      >
        <i class="fas fa-search"></i>

        <p>Filtern</p>
      </button>
    </form>
  </div>
</div>
<div
  class="blog_posts {%if blogPosts.count == 1%} blog_post_1_grid {% elif blogPosts.count == 2 %} blog_post_2_grid {% else %}blog_post_3_grid {% endif %}"
>
  {%if blogPosts.count == 0%}
  <div class="galerie_kein_bild">
    <img
      style="display: block; margin-left: auto; margin-right: auto"
      src="{%static 'images/iconmonstr-magnifier-2-240.png'%}"
      alt=""
    />
    <h1>Kein Blog Post bisher.</h1>
  </div>
  {% endif %} {% for blogPost in blogPosts %}
  <div class="blog_post">
    <div class="blog_post_card">
      <a
        style="
          color: black;
          display: flex;
          flex-direction: column;
          align-items: center;
        "
        href="/blog/{{blogPost.uuid}}"
        ><h3>{{blogPost.titel}}</h3>
        <img
          {%
          if
          blogPost.bild.url
          !=""
          %}
          src="../../static{{blogPost.bild.url}}"
          {%
          endif
          %}
          alt=""
          style="width: 40%"
      /></a>
      <p>Von {{blogPost.autor}} am {{blogPost.date}}</p>

      <p style="margin: 0">{{blogPost.snippet}}</p>
      <a style="margin-bottom: 5px" href="/blog/{{blogPost.uuid}}"
        >Weiterlesen</a
      >
    </div>
    {% if user.is_superuser %}

    <div class="blog_post_funktion">
      <form
        action="/{{blogPost.uuid}}/blogPostbearbeiten"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <button
          type="button"
          class="btn btn-outline-primary btn-sm"
          data-toggle="modal"
          data-target="#editBlogPostModal{{blogPost.uuid}}"
        >
          <i class="fas fa-edit"></i>
        </button>

        <div
          class="modal fade"
          id="editBlogPostModal{{blogPost.uuid}}"
          tabindex="-1"
          role="dialog"
          aria-labelledby="editBlogPostModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5
                  style="color: black"
                  class="modal-title"
                  id="editBlogPostModalTitle"
                >
                  BlogPost bearbeiten
                </h5>

                <button
                  class="close"
                  style="
                    background-color: transparent;
                    outline: none;
                    border: none;
                  "
                  type="button"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <input
                  type="text"
                  name="edittitel"
                  maxlength="50"
                  required=""
                  id="id_titel"
                  value="{{blogPost.titel}}"
                />

                <input
                  type="text"
                  name="editinhalt"
                  id="id_inhalt"
                  maxlength="2000"
                  required
                  value="{{blogPost.inhalt}}"
                />
                <input type="date" name="editdate" id="id_date" />
                <input
                  type="text"
                  required
                  name="editstandort"
                  id="id_standort"
                  value="{{blogPost.standort}}"
                />
                <input type="file" name="editbild" id="id_bild" />
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Schließen
                </button>
                <button class="btn btn-primary" type="submit">
                  Bearbeiten
                </button>
              </div>
            </div>
          </div>
        </div>
      </form>

      <form action="/{{blogPost.uuid}}/blogPostdelete" method="POST">
        {% csrf_token %}
        <button
          type="button"
          class="btn btn-outline-danger btn-sm"
          data-toggle="modal"
          data-target="#deleteBlogPostModal{{blogPost.uuid}}"
        >
          <i class="fas fa-trash"></i>
        </button>

        <div
          class="modal fade"
          id="deleteBlogPostModal{{blogPost.uuid}}"
          tabindex="-1"
          role="dialog"
          aria-labelledby="deleteBlogPostModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5
                  style="color: black"
                  class="modal-title"
                  id="deleteBlogPostModalTitle"
                >
                  BlogPost löschen
                </h5>

                <button
                  class="close"
                  style="
                    background-color: transparent;
                    outline: none;
                    border: none;
                  "
                  type="button"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <h6 style="color: black">Wirklich löschen?</h6>
                <h6 style="color: black">
                  Der Blog Post wird endgültig gelöscht und kann nicht
                  wiederhergestellt werden.
                </h6>
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Schließen
                </button>
                <button class="btn btn-danger" type="submit">Löschen</button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>

    {% endif %}
  </div>
  {% endfor %}
</div>

{% if user.is_superuser %}
<div class="termin_erstellen add">
  <form
    action="/createblogPost"
    method="POST"
    enctype="multipart/form-data"
    id="blog_post_hinzufuegen_wrapper"
    class="hidden"
  >
    {% csrf_token %} {{blogForm}}
    <p style="display: inline-block">* : erforderlich</p>

    <button class="btn btn-primary btn-sm" type="submit">Erstellen</button>
    <i
      style="
        position: absolute;
        right: 5px;
        top: 5px;
        color: red;
        cursor: pointer;
        font-size: 20px;
      "
      class="fas fa-times-circle"
      style="color: red"
      id="blog_post_hinzufuegen_close"
    ></i>
  </form>
  <div
    class="short_hinzufuegen"
    style="cursor: pointer"
    id="blog_post_short_hinzufuegen"
  >
    <i class="fas fa-plus"></i> Blog Post hinzufügen
  </div>
</div>

{% endif %} {% endblock content %} {% block script %}
<script>
  let filterbtn = document.getElementById('filtericon');
  let filter = document.getElementById('filter')
  filterbtn.onclick = function () {
    filter.classList.toggle('active');
    filterreset.classList.toggle('active');

  };
  close = document.getElementById('blog_post_hinzufuegen_close');
  show = document.getElementById('blog_post_short_hinzufuegen');

  close.onclick = function () {
    document
      .getElementById('blog_post_hinzufuegen_wrapper')
      .classList.add('hidden');
    show.classList.remove('hidden');
  };
  show.onclick = function () {
    document
      .getElementById('blog_post_hinzufuegen_wrapper')
      .classList.remove('hidden');
    show.classList.add('hidden');
  };
</script>
{% endblock script %}

tennisclub/templates/courts_teppichboden_preise_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div style="height:90vh;">

<embed src="{%static 'images/Teppichboden_Preise.pdf'%}" type="application/pdf" width=100% height=100% />
</div>
{% endblock content %}

tennisclub/templates/heim.html
{% extends 'base.html' %}

{% block content %}

<h1>Rückblick</h1>

{% endblock content %}

tennisclub/templates/impressum.html
{% extends 'base.html' %}


{% block content %}

<p> Websiteentwurf für den TC-Hallstadt. <br>
    Bei Problemen mit der Website kontaktieren Sie bitte: <br>
    Michel Berwind <br>
    Eichelberger Weg 4 <br>
    96106 Ebern-Heubach <br>
    michel.berwind@web.de <br>
</p>

{% endblock content %}

tennisclub/templates/kontakt.html
{% extends 'base.html' %}

{% block content %}

<h1>Kontakt</h1>

{% endblock content %}

tennisclub/templates/regeln.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1 style="padding:10px;">Platzregeln</h1>

<div style="padding:10px; font-size: 20px;">
    16 Mannschaften spielen in diesem Jahr für den TC Hallstadt; sie alle wollen trainieren, das erfordert mehr als bisher genaue Einhaltung der Regeln bei der Platzbelegung.

    <br><br>
    Die Platzbelegung muss auf dem Bildschirm im Clubhaus erkennbar sein; keiner spielt ohne reguläre Belegung des Platzes!

    <br><br>
    Zunächst sollte als Grundsatz gelten: alle Spieler, die die Möglichkeit haben, vor 18.00, noch besser vor 17.00 Uhr ihr Einzel oder Doppel auszutragen, sollten das unbedingt tun.
    <br>
    Ab 17.00 Uhr sind die Plätze den berufstätigen Mitgliedern vorbehalten. (Ausnahme: die Trainerplätze)

    <br><br>
    Trainingsplätze für die Mannschaften sind für die Zeit der Medenspiele (Ende April bis Ende Juli) fest eingerichtet, danach wird die Reservierung entfernt.
    <br>
    Die Mitglieder der Mannschaften haben auch dann ein Anrecht auf die Plätze, wenn sie zu spät kommen.

    <br><br>
    Für das Mannschaftstraining dürfen keine zusätzlichen Plätze reserviert werden!

    <br><br>
    Die wenigen Plätze, die nicht von Mannschaften belegt sind, dürfen ab 18.00 Uhr nur für eine Stunde (Einzel) reserviert werden; auch das Eintragen vorgeblicher Nachfolger ist in diesem Zeitraum nicht gestattet. Länger als eine Stunde kann auch zu weniger belebten Zeiten nur dann gespielt werden, wenn kein Nachfolger den Platz beansprucht.
    <br>
    Ein von Freizeitspielern reservierter Platz darf nach 10-minütiger Wartezeit auch von anderen genutzt werden.

    <br><br>
    Selbstverständlich sollte für alle Spieler die Pflege der Plätze sein:
    Vor dem Spiel: Der Platz darf nie in staubstrockenem Zustand bespielt werden.
    Nachher: Der Platz wird abgezogen, bei Bedarf gewässert und die Linien werden gekehrt.

    <br><br>
    Wir behalten uns vor, alle zu korrigieren, die sich nicht an diese Regeln halten.
    <br><br>
    Die Vorstandschaft
</div>

<a style="padding:10px; font-size: 20px;" href="{%static 'images/PlatzbelegungsRegeln.pdf'%}"> Platzbelegungs-Regeln als PDF-Dokument </a>



{% endblock content %}

tennisclub/templates/verein.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="wrapper">
    <div class="slider">
        <img src="{% static 'images/ClubHaus_Neu_350.jpg'%}" alt="" class="slide_bild">
    </div>

    <div class="tenniscourts">
        <h2>Unsere Tenniscourts</h2>
        <img src="" alt="Beispielbild">
        <img src="Beispielbild" alt="">
    </div>
</div>

{% endblock content %}